[tool.black]
line-length = 100

include = '\.pyi?$'

exclude = '''
(
      __pycache__
    | \.git
    | \.mypy_cache
    | \.pytest_cache
    | \.vscode
    | \.venv
    | \bdist\b
    | \bdoc\b
)
'''

[tool.flake8]
max-line-length = 115

ignore =
    # these rules don't play well with black
    # whitespace before :
    E203
    # line break before binary operator
    W503
    E241,E305,W504,W605,E731


exclude =
    .venv
    .git
    __pycache__
    docs/build
    dist
    .mypy_cache
    __init__.py
    docs/auto_examples/*
    docs/_build/*

per-file-ignores =
    # __init__.py files are allowed to have unused imports and lines-too-long
    */__init__.py:F401
    */**/**/__init__.py:F401,E501


[tool.mypy]
ignore_missing_imports = true
no_site_packages = true
allow_redefinition = True
exclude = _script.py

[tool.mypy-tests.*]
strict_optional = false

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
